name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # needed to push to output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Prince-git-hub-360
          outputs: 
            - dist/snake.svg
            - dist/snake.gif
          theme: github-dark  # transparent background

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
