name: Generate Snake

on:
  # Run automatically whenever you push to main branch
  push:
    branches:
      - main

  # Run every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allow manual run
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
